### ISSUE TITLE
Too many generators in example

### ISSUE THREAD

**Issue by Tastalian** [mcmtroffaes/pycddlib#14]
Hi there,

Every time I use pycddlib, I have a somewhat difficult time figuring out the signs of the inputs. The documentation points to cddlib examples, which are not so self-explanatory...

Anyway, I came up with the following function to convert between the face and span matrices of a polyhedral cone:

    def span_of_face(F):
        """
        Compute the span matrix S of the face matrix F, that is, a matrix such that
        {F x <= 0} iff {x = S z,  for some vector z >= 0}.
        """
        b, A = zeros((F.shape[0], 1)), F
        # H-representation: b - A x >= 0
        # ftp://ftp.ifor.math.ethz.ch/pub/fukuda/cdd/cddlibman/node3.html
        # the input to pycddlib is [b, -A]
        F_cdd = Matrix(hstack([b, -A]), number_type='float')
        F_cdd.rep_type = RepType.INEQUALITY
        P = Polyhedron(F_cdd)
        V = array(P.get_generators())
        for i in xrange(V.shape[0]):
            print "V[%d, 0] =" % i, V[i, 0]
        return V[:, 1:].T

The problem is, if I take the generators for the cone (x <= 0, y <= 0) in 3D (variables x, y, z), i.e.

    In [2]: span_of_face(array([[1, 0, 0], [0, 1, 0]]))

I get:

    V[0, 0] = 0.0
    V[1, 0] = 0.0
    V[2, 0] = 0.0
    Out [2]: 
    array([[-1., -0.,  0.],
       [ 0., -1.,  0.],
       [ 0.,  0.,  1.]])

Why did a third generator (z >= 0) appear? Looking at the generators V, it is furthermore undistinguishable from the two other rays (x <= 0) and (y <= 0)...

**Comment by Tastalian** [comment]
Sorry, I realize my mistake, my input was not a polyhedral convex cone.

However, pycddlib silently made an arbitrary choice (z >= 0 rather than z <= 0). Is this behavior documented somewhere? Shouldn't at least a warning be raised in such situations?

**Comment by mcmtroffaes** [comment]
``` {.python}
import cdd
from numpy import *

def span_of_face(F):
    """
    Compute the span matrix S of the face matrix F, that is, a matrix such that
    {F x <= 0} iff {x = S z,  for some vector z >= 0}.
    """
    b, A = zeros((F.shape[0], 1)), F
    # H-representation: b - A x >= 0
    # ftp://ftp.ifor.math.ethz.ch/pub/fukuda/cdd/cddlibman/node3.html
    # the input to pycddlib is [b, -A]
    F_cdd = cdd.Matrix(hstack([b, -A]), number_type='float')
    F_cdd.rep_type = cdd.RepType.INEQUALITY
    P = cdd.Polyhedron(F_cdd)
    g = P.get_generators()  # NEW LINE HERE
    print(g.lin_set)  # NEW LINE HERE
    V = array(g)
    for i in xrange(V.shape[0]):
        print "V[%d, 0] =" % i, V[i, 0]
    return V[:, 1:].T

print(span_of_face(array([[1, 0, 0], [0, 1, 0]])))
```

shows that z is unconstrained as the third row is in the linearity set:

```
frozenset([2])
V[0, 0] = 0.0
V[1, 0] = 0.0
V[2, 0] = 0.0
[[-1. -0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]
```

(if I understand the cddlib documentation correctly...)

Does this help?

**Comment by Tastalian** [comment]
Thank you :) Indeed that's exactly the piece of information that was missing here.
