### ISSUE TITLE
Setting a Polygon's rep_type causes a segfault crash

### ISSUE THREAD

**Issue by haudren** [mcmtroffaes/pycddlib#16]
Hello,

I was tinkering with pycddlib to check whether `dd_DDInputAppend` does or does not work. After analysis of the source code, it does *not*, quote:
> /* This is imcomplete.  It simply solves the problem from scratch.  */

But the interesting thing is that it changes the polyhedron's representation type on line 323 of cddlib.c:
> (*poly)->representation=dd_Inequality;

I have no idea why this is done. However, trying to do the same in Python:
https://gist.github.com/haudren/74f59121e902e2026847

Results in:
> [1]    5776 segmentation fault  python test_extend_poly.py

Gdb backtrace (quick and dirty):
```gdb
Program received signal SIGSEGV, Segmentation fault.
__pyx_setprop_3cdd_10Polyhedron_rep_type (o=0x7ffff3327dc8, v=<optimized out>, x=<optimized out>)
    at cdd.c:11259
11259	    return __pyx_pw_3cdd_10Polyhedron_8rep_type_3__set__(o, v);
(gdb) bt
#0  __pyx_setprop_3cdd_10Polyhedron_rep_type (o=0x7ffff3327dc8, v=<optimized out>, x=<optimized out>)
    at cdd.c:11259
#1  0x00000000004ad23a in _PyObject_GenericSetAttrWithDict ()
#2  0x00000000004ad9dd in PyObject_SetAttr ()
#3  0x000000000049a356 in PyEval_EvalFrameEx ()
#4  0x00000000004a1634 in ?? ()
#5  0x000000000044e4a5 in PyRun_FileExFlags ()
#6  0x000000000044ec9f in PyRun_SimpleFileExFlags ()
#7  0x000000000044f904 in Py_Main ()
#8  0x00007ffff7818ec5 in __libc_start_main (main=0x44f9c2 <main>, argc=2, argv=0x7fffffffe448, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe438)
    at libc-start.c:287
#9  0x0000000000578c4e in _start ()
```

I am not sure that anyone should *ever* have to change a polyhedron's representation, so I am not sure this is really useful. I quickly checked cdd's documentation but could not find any trace of when/why one should set a polyhedron's RepType.

**Comment by mcmtroffaes** [comment]
Fixed.
