### ISSUE TITLE
There is no functioning python wheel for Python 3.6

### ISSUE THREAD

**Issue by CookieChief** [mcmtroffaes/pycddlib#18]

**Comment by mcmtroffaes** [comment]
Well, there are wheels for 3.6, but they have not yet been released as I haven't had the chance to test them properly yet. Could you test (one of) these beta release wheels and see if (one of them) works?

64 bit: https://ci.appveyor.com/api/buildjobs/q1v5pcp2y0v0dipi/artifacts/dist%2Fpycddlib-1.0.6a0-cp36-cp36m-win_amd64.whl
32 bit: https://ci.appveyor.com/api/buildjobs/0g0lyvldogpvyj7m/artifacts/dist%2Fpycddlib-1.0.6a0-cp36-cp36m-win32.whl

**Comment by CookieChief** [comment]
Hi thanks for your quick and helpful response!

`pip install <name of wheel>` is sucessfull. However when trying to import the package in python by 

`import pycddlib` it throws an error _package pycddlib not found_. Looking into the directory where my packages are installed I can find a **pycddlib-1.0.6a0.dist-info** folder. However there is **pycddlib** folder as for all other packages. 

I am not sure if thats a problem with the wheel or with me or my system. Any suggestions?

**Comment by mcmtroffaes** [comment]
I think you're importing the wrong module. Did you try ``import cdd``? There's no folder for the package, it's just a single binary module contained in a single file called ``cdd.cp36-win_amd64.pyd``, which you should see in your installation (hopefully!).

**Comment by CookieChief** [comment]
Now importing works great thanks a lot!

**Comment by mcmtroffaes** [comment]
Ok thanks for confirming! I'll push a release soon.

**Comment by CookieChief** [comment]
Great :)

**Comment by mcmtroffaes** [comment]
The python 3.6 wheels have now been released. Thanks again for helping to test!
