### ISSUE TITLE
GMP not listed as a dependency

### ISSUE THREAD

**Issue by marcusps** [mcmtroffaes/pycddlib#2]
Attempting to install `pycddlib` without GMP installed causes build failure. Running
```
pip install pycddlib
```
results in a (very long) error message that begins with
```
Collecting pycddlib
  Downloading pycddlib-1.0.4.zip (246kB)
    100% |################################| 249kB 446kB/s 
    warning: no directories found matching 'docs/_build/html'
Installing collected packages: pycddlib
  Running setup.py install for pycddlib
    building 'cdd' extension
    gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -DGMPRATIONAL -Icddlib/lib-src -Icddlib/lib-src-gmp -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c cdd.c -o build/temp.macosx-10.6-x86_64-2.7/cdd.o
    In file included from cddlib/lib-src/cdd.h:18,
                     from cdd.c:277:
    cddlib/lib-src/cddmp.h:34:18: error: gmp.h: No such file or directory
```

After installing GMP (in my case, via homebrew), everything runs smoothly.

**Comment by mcmtroffaes** [comment]
It is mentioned in the documentation:

http://pycddlib.readthedocs.org/en/latest/quickstart.html#building-from-source

As far as I know there is no simple way to list C libraries as dependencies in setup.py to give a more meaningful error message...

**Comment by marcusps** [comment]
Yeah, I hoped `setuptools` would have something, but I looked around briefly and could not find anything (although I am not well versed on `setuptools`).

**Comment by mcmtroffaes** [comment]
I cannot find anything either; closing for now...
