### ISSUE TITLE
Different behaviour between python 2 and 3 on rational matrices

### ISSUE THREAD

**Issue by haudren** [mcmtroffaes/pycddlib#20]
I am currently trying to convert my [old python2-only code](https://github.com/haudren/pyparma) into python3-compatible code. I had zero problems to install pycddlib. However, my tests keep failing. I narrowed the problem down to the following snippet:

```python
from __future__ import print_function
import numpy as np
import cdd

A = np.array([[1, 0, 0],
              [1, 1, 0],
              [1, 0, 1]])

mat = cdd.Matrix(A, number_type='fraction')
mat.rep_type = cdd.RepType.GENERATOR
cdd_poly = cdd.Polyhedron(mat)

ineq = np.array(cdd_poly.get_inequalities())
print(ineq)
```

Using `python2`:
```
[[ 1 -1 -1]
 [ 0  1  0]
 [ 0  0  1]]
```

Using `python3`:
```
[[0 1 0]
 [0 0 1]]
```

I am using Python 2.7.6 and Python 3.4.3 for the comparison, while pycddlib is at 1.0.5 on both configurations. Any idea why the Python 3 version would drop the very first inequality ?

Note that if I use non-rational coefficients, the difference in behaviour disappears.

**Comment by haudren** [comment]
Ok, so I tracked it down a bit more:
```python
A = [[1]]
mat = cdd.Matrix(A, number_type='fraction')
print(mat)

A = np.array(A)
mat = cdd.Matrix(A, number_type='fraction')
print(mat)
```

This shows that there is an issue with the conversion from numpy arrays in python3. It might be because I'm running `1.11.1` in `python2` and `1.13.3` in `python3`.

**Comment by haudren** [comment]
Sorry for the spam, I guess it is related to those issues:
https://github.com/cvxopt/cvxopt/issues/85

In python3, `np.int64` is no longer a subclass of `int`, which probably explains the behaviour...

**Comment by mcmtroffaes** [comment]
Ok no problem, thanks for tracking this down!

**Comment by haudren** [comment]
Note that this can probably be fixed by changing [this](https://github.com/mcmtroffaes/pycddlib/blob/develop/cdd.pyx#L215) to:
```python
elif isinstance(value, (Fraction, int, long, np.integer)):
```

`np.integer` covers all of numpy's integer types (e.g. `int64`, `int32`).

**Comment by mcmtroffaes** [comment]
You're correct. However pulling in numpy as a dependency just to fix this sounds like the wrong thing to do. I wonder if we could rely on https://docs.python.org/2/library/numbers.html (numbers.Rational in particular).

**Comment by haudren** [comment]
It seems like it would work, at least on python3.4:
```python
import numbers
import numpy as np

a = np.int64(2)
isinstance(a, numbers.Rational)  # True
isinstance(a, int) # False
```

I will try to implement this in pycddlib an submit a PR

**Comment by mcmtroffaes** [comment]
Quick update: I've changed the behaviour of NumberTypeable so all numbers.Rational types are recognized and will result in a rational matrix to be used - this seems more consistent and less surprising. I've bumped the major version because this is technically speaking a change in the interface.

**Comment by haudren** [comment]
That sounds great, thanks!
