### ISSUE TITLE
generating vertices of LP optimal solutions

### ISSUE THREAD

**Issue by sdementen** [mcmtroffaes/pycddlib#23]
I have successfully solved an LP with pycddlib of the form
```
max c.x
st A.x <= b
```
I need to generate the set of vertices for the optimal solutions of both this primal problem and its dual.
If I am not mistaken, it is exactly what pycddlib is good at ! But I can't figure out from the documentation how to do it. Could you give me some hints ?

If it can be of any help, here is the problem
```
begin
 19 13 rational
 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1
 2 -1 -1 -1 0 0 0 0 0 0 0 0 0
 1 0 0 0 -1 -1 -1 0 0 0 0 0 0
 2 0 0 0 0 0 0 -1 -1 -1 0 0 0
 2 0 0 0 0 0 0 0 0 0 -1 -1 -1
 1 -1 0 0 -1 0 0 -1 0 0 -1 0 0
 2 0 -1 0 0 -1 0 0 -1 0 0 -1 0
 3 0 0 -1 0 0 -1 0 0 -1 0 0 -1
end
maximize
 0 8 6 3 7 5 2 6 4 1 6 4 1
```
with the python code
```
import cdd
mat = cdd.Matrix([[ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1],
       [ 2, -1, -1, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  0,  0, -1, -1, -1,  0,  0,  0,  0,  0,  0],
       [ 2,  0,  0,  0,  0,  0,  0, -1, -1, -1,  0,  0,  0],
       [ 2,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1, -1, -1],
       [ 1, -1,  0,  0, -1,  0,  0, -1,  0,  0, -1,  0,  0],
       [ 2,  0, -1,  0,  0, -1,  0,  0, -1,  0,  0, -1,  0],
       [ 3,  0,  0, -1,  0,  0, -1,  0,  0, -1,  0,  0, -1]], number_type='fraction')
mat.obj_type = cdd.LPObjType.MAX
mat.obj_func = [0, 8, 6, 3, 7, 5, 2, 6, 4, 1, 6, 4, 1]
print(mat)
print(mat.obj_func)
lp = cdd.LinProg(mat)
lp.solve()
lp.status == cdd.LPStatusType.OPTIMAL

print(lp.obj_value)
print(" ".join("{0}".format(val) for val in lp.primal_solution))
print(" ".join("{0}".format(val) for val in lp.dual_solution))
```

**Comment by sdementen** [comment]
An LP can have as solution x a polyhedron no?

**Comment by stephane-caron** [comment]
Aah, that's right! The set of optimal solutions is indeed a face of the initial polyhedron, and what you want is to enumerate vertices of the face corresponding to your optimal solution.

I don't know how to do this directly with cdd.

What I would do off the top of my head is:
- Take the optimal solution `x*`
- Enumerate its active set, i.e. the set ``act`` of constraint indexes s.t. ``A_act x* == b_act``
- Call vertex enumeration (function above) on the face ``{A x <= b, A_act x == b_act}``; or, use the function call above and just discard vertices ``v`` for which ``A_act v != b_act``
- Apply the same to the dual

That's definitely not efficient since the LP solver already knows the active set internally.

Looking forward to a more elegant solution :wink:

**Comment by mcmtroffaes** [comment]
One way is to add a constraint to fix the value of the optimal solution, and then to enumerate the vertices of the resulting extended problem. More elegantly, the simplex method can (in principle) also be used to enumerate all optimal solutions, without having to resolve an extended problem from scratch. I'm not sure how to do that with cdd. Regardless, none of this has any bearing on the Python interface of cddlib, so I will close this. I suggest that you address your maths questions to mathoverflow instead, to find out the best method for doing what you want to do.
