### ISSUE TITLE
Segfault on empty polyhedron?

### ISSUE THREAD

**Issue by JoostvanPinxten** [mcmtroffaes/pycddlib#25]
First off, thanks for making a Python wrapper for the cdd-lib, this has been very useful in combining my research experiments with matplotlib in a Jupyter notebook.

That being said, I encounter segfaults due to the wrapper. And with the use of the _faulthandler_ module and _ipdb_ I was able to construct the following (minimal) reproducable example:

```python
import cdd

def create(): 

    some_rows = []
    mat = cdd.Matrix(some_rows, number_type='fraction')
    mat.rep_type = cdd.RepType.INEQUALITY
    return mat

def func():
    mat = create()
    print(mat)
    # running the script with the following line not commented will trigger a segfault
    # poly = cdd.Polyhedron(mat)

func()
print("finished")
```

It basically constructs an empty polyhedron (which is valid in _cdd_ as far as I'm aware). But it segfaults on cleaning up the polyhedron!

I've noticed some weird behaviour in Jupyter notebook, as running the script cell _without_ ```poly=cdd.Polyhedron(mat)``` first, and then running _with_ that line does _not_ lead to a segfault.

If you could shed some light on why this might be happening, I'll be willing to have a look at the Cython code to see whether this can be easily fixed. I'm assuming that somewhere in a `__dealloc__` there is some _free()_ issue.

**Comment by JoostvanPinxten** [comment]
Valgrind reports the following, however, I don't know which part of the cdd.pyx file transforms into the dealloc C-functions:

```
Conditional jump or move depends on uninitialised value(s)
   at free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
   by dd_FreePolyhedra (cddcore.c:566)
   by __pyx_pf_3cdd_10Polyhedron_6__dealloc__ (cdd.c:14220)
   by __pyx_pw_3cdd_10Polyhedron_7__dealloc__ (cdd.c:14192)
   by __pyx_tp_dealloc_3cdd_Polyhedron (cdd.c:20408)
   by fast_function (in **/bin/python3.6)
   by call_function (in **/bin/python3.6)
   by _PyEval_EvalFrameDefault (in **/bin/python3.6)
   by PyEval_EvalCodeEx (in **/bin/python3.6)
   by PyEval_EvalCode (in **/bin/python3.6)
   by run_mod (in **/bin/python3.6)
   by PyRun_FileExFlags (in **/bin/python3.6)
   by PyRun_SimpleFileExFlags (in **/bin/python3.6)
   by Py_Main (in **/bin/python3.6)
```

**Comment by JoostvanPinxten** [comment]
The following C-program does not segfault, even though valgrind does report that `dd_FreePolyhedra()` does have a jump depending on an uninitialized value:

```C
#include <stdio.h>
#include <setoper.h>
#include <cdd.h>

int main(int argc, char* argv[])
{

    dd_set_global_constants();

    dd_MatrixPtr mat;

    dd_ErrorType error = dd_NoError;

    mat = dd_CreateMatrix(0,0);
    mat->numbtype = dd_Integer;

    dd_PolyhedraPtr poly = dd_DDMatrix2Poly(mat, &error);

    if(error != dd_NoError)
        printf("dd_error set\n");

    if(mat == NULL)
        printf("NULL matrix returned\n");

    printf("freeing the polyhedron\n");
    dd_FreePolyhedra(poly);
    dd_free_global_constants();
    return 0;
}
```

**Comment by mcmtroffaes** [comment]
Thanks for reporting. I've added a test case for this. The bug is in cddlib itself, I suspect. I think I've found a fix for this, will report to cddlib momentarily.

**Comment by mcmtroffaes** [comment]
Could you confirm that this patch (posted to cddlib already since even if it doesn't fix this issue, it will certainly prevent some other issues) fixes the problem for you?

https://github.com/cddlib/cddlib/pull/21/commits/d7bbc21308e88a0445640af9c6d6b91c64497c34

**Comment by JoostvanPinxten** [comment]
Indeed, this seems to be a small oversight in cddlib itself. The fix you provided does fix the particular problem, but it encounters another `Conditional jump or move depends on uninitialised value(s)` in [dd_FreePolyhedra (cddcore.c:566)](https://github.com/cddlib/cddlib/blob/d7bbc21308e88a0445640af9c6d6b91c64497c34/lib-src/cddcore.c#L566)

**Comment by mcmtroffaes** [comment]
Since this bug is purely upstream, let's continue the discussion on the cddlib bug tracker.
