### ISSUE TITLE
Auto-install Cython dependency?

### ISSUE THREAD

**Issue by stephane-caron** [mcmtroffaes/pycddlib#27]
In this issue https://github.com/stephane-caron/lpsolvers/issues/1 a user reported an installation error when installing pycddlib via pip: Cython was not present on his system, and the installation broke with an error.

I'm not sure why Cython was not installed automatically by pip: shouldn't it be, since it is listed in `setup_requirements.txt`?

**Comment by mcmtroffaes** [comment]
Should be fixed now - thanks for reporting!
