### ISSUE TITLE
Max string length is too small

### ISSUE THREAD

**Issue by dimy93** [mcmtroffaes/pycddlib#39]
You set it to 20000 but mere 92 x 6,  V-representation created from H-representation on floats and converted to fractions cuts 2/3 of the file. Please substaintially increase it or even better get rid of it all together. Another option will be to create actual API for writting to files. In either case as it is it's unusuable

**Comment by mcmtroffaes** [comment]
Sure, the cddlib file writing API could be exposed directly. I'd prefer also to patch the __str__ method properly. One way might be to let _tmpread read in chunks and then to use [PyUnicode_DecodeUTF8Stateful](https://docs.python.org/3.7/c-api/unicode.html#c.PyUnicode_DecodeUTF8Stateful) and join the decoded chunks together. Happy to take a patch.
