### ISSUE TITLE
Undefined behavior of Matrix.canonicalize()

### ISSUE THREAD

**Issue by Tastalian** [mcmtroffaes/pycddlib#4]
Hello,

The behavior of Matrix.canonicalize() is not specified when the field `repr_type` is `cdd.ReprType.UNSPECIFIED`. 
Taking the example from the doc, I get two different behaviors:

    In [22]: mat = cdd.Matrix([[2, 1, 2, 3], [0, 1, 2, 3], [3, 0, 1, 2], [0, -2, -4, -6]], number_type='fraction')
    In [23]: mat.rep_type = cdd.RepType.GENERATOR
    In [24]: mat.canonicalize()
    Out[24]: (frozenset({1, 3}), frozenset())

Versus:

    In [25]: mat = cdd.Matrix([[2, 1, 2, 3], [0, 1, 2, 3], [3, 0, 1, 2], [0, -2, -4, -6]], number_type='fraction')
    In [26]: mat.rep_type = cdd.RepType.INEQUALITY
    In [27]: mat.canonicalize()
    Out[27]: (frozenset({1, 3}), frozenset({0}))

Shouldn't there be a check here to avoid user mistakes?

**Comment by mcmtroffaes** [comment]
pycddlib tries hard not to do anything cddlib wouldn't do:

https://github.com/mcmtroffaes/pycddlib/blob/develop/cdd.pyx#L635

... but I agree, it would be pythonic to help the user shooting herself/himself in the foot, for instance by raising a ValueError.

**Comment by mcmtroffaes** [comment]
Now fixed on develop. Thanks again for reporting!
