### ISSUE TITLE
Wrong conversion between V- and H-representation

### ISSUE THREAD

**Issue by timzieger** [mcmtroffaes/pycddlib#40]
In the below I give an example for an attempt to go back and forth between the vertex and halfspace representation. Apparently there is a problem with the conversion to the halfspace representation since the inequalities correspond to an unbounded Polyhedron instead of a segment. Would be great if someone could have a look at it:

# Code
    lhv = [[1, -0.00008,  0.00933],[1, 0.00008, -0.00933]]       # [t, segment_vertices]
    mat = cdd.Matrix(lhv, number_type='float')
    mat.rep_type = cdd.RepType.GENERATOR
    P = cdd.Polyhedron(mat)
    print(P.get_generators())                                    # prints correct vertices
    
    mat2 = cdd.Matrix(P.get_inequalities(),number_type='float')             
    mat2.rep_type = cdd.RepType.INEQUALITY
    P2 = cdd.Polyhedron(mat2)
    print(P2.get_generators())                                   # prints vertices + an additional row representing a ray
    
    # using fractions
    from fractions import Fraction 
    
    lhv = [[Fraction(1), Fraction(-0.00008),  Fraction(0.00933)],
           [Fraction(1), Fraction(0.00008), Fraction(-0.00933)]]
    mat = cdd.Matrix(lhv, number_type='fraction')
    mat.rep_type = cdd.RepType.GENERATOR
    P = cdd.Polyhedron(mat)
    print(P.get_generators())
    
    mat2 = cdd.Matrix(P.get_inequalities(),number_type='fraction')
    mat2.rep_type = cdd.RepType.INEQUALITY
    P2 = cdd.Polyhedron(mat2)
    print(P2.get_generators())                                   # same problem as with float

This is what I get:

# Output
V-representation
begin
 2 3 real
  1 -8.000000000E-05  9.330000000E-03
  1  8.000000000E-05 -9.330000000E-03
end
V-representation
begin
 3 3 real
  1  7.729894423E-05 -9.329080582E-03
  1 -7.729894423E-05  9.329080582E-03
  0  0  1
end
V-representation
begin
 2 3 rational
 1 -5902958103587057/73786976294838206464 5378378818990941/576460752303423488
 1 5902958103587057/73786976294838206464 -5378378818990941/576460752303423488
end
V-representation
begin
 3 3 real
  1  7.729894423E-05 -9.329080582E-03
  1 -7.729894423E-05  9.329080582E-03
  0  0  1
end

**Comment by mcmtroffaes** [comment]
You forgot to express that the 3rd constraint is an equality (as ``print(P.get_inequalities())`` will show) in the H representation, e.g.

```python
mat2.lin_set = [2]
```

**Comment by timzieger** [comment]
Thank you very much for this quick answer and sorry my misunderstanding.
