### ISSUE TITLE
Compilation error when install pycddlib for python3.6

### ISSUE THREAD

**Issue by JacksonZyy** [mcmtroffaes/pycddlib#43]
Hi!
I try to install pycddlib on ububtu using "python3.6 -m pip install pycddlib" but the build fails with the following error:
```
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7owi306n/pycddlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7owi306n/pycddlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bosupvfh/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/pycddlib
         cwd: /tmp/pip-install-7owi306n/pycddlib/
    Complete output (16 lines):
    running install
    running build
    running build_ext
    skipping 'cdd.c' Cython extension (up-to-date)
    building 'cdd' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/cddlib
    creating build/temp.linux-x86_64-3.6/cddlib/lib-src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DGMPRATIONAL -Icddlib/lib-src -I/usr/include/python3.6m -c cdd.c -o build/temp.linux-x86_64-3.6/cdd.o
    In file included from cdd.c:14:0:
    /usr/include/python3.6m/Python.h:39:19: fatal error: crypt.h: No such file or directory
     #include <crypt.h>
                       ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
Basically, the problem is for crypt.h: No such file or directory
I actually found crypt.h as in /usr/include/crypt.h, but it was empty when I checked the content.
Can you help me solve this problem?
Thank you!

**Comment by JacksonZyy** [comment]
> Hi!
> I try to install pycddlib on ububtu using "python3.6 -m pip install pycddlib" but the build fails with the following error:
> 
> ```
> ERROR: Command errored out with exit status 1:
>      command: /usr/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7owi306n/pycddlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7owi306n/pycddlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bosupvfh/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/pycddlib
>          cwd: /tmp/pip-install-7owi306n/pycddlib/
>     Complete output (16 lines):
>     running install
>     running build
>     running build_ext
>     skipping 'cdd.c' Cython extension (up-to-date)
>     building 'cdd' extension
>     creating build
>     creating build/temp.linux-x86_64-3.6
>     creating build/temp.linux-x86_64-3.6/cddlib
>     creating build/temp.linux-x86_64-3.6/cddlib/lib-src
>     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DGMPRATIONAL -Icddlib/lib-src -I/usr/include/python3.6m -c cdd.c -o build/temp.linux-x86_64-3.6/cdd.o
>     In file included from cdd.c:14:0:
>     /usr/include/python3.6m/Python.h:39:19: fatal error: crypt.h: No such file or directory
>      #include <crypt.h>
>                        ^
>     compilation terminated.
>     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> ```
> 
> Basically, the problem is for crypt.h: No such file or directory
> I actually found crypt.h as in /usr/include/crypt.h, but it was empty when I checked the content.
> Can you help me solve this problem?
> Thank you!

I solved this problem myself. I have another server with pycddlib successfully installed. So I copy the crypt.h in that server to this one, then I can compile and install successfully, hope this can help others.

**Comment by mcmtroffaes** [comment]
Glad you figured out a solution. I suspect you were missing some development libraries/headers for compiling extension modules.
