### ISSUE TITLE
Minkowski Summation and Pontryagin difference

### ISSUE THREAD

**Issue by CWEzio** [mcmtroffaes/pycddlib#48]
Hi, I have a quesiton about whether pycddlib has functions on Minkowski Summation and Pontryagin difference operations like MPT3. I am looking for python alternative for matlab's MPT3 toolbox's computational geometry function. As far as I know, MPT3 also use cddlib for handling polyhedra.

Thank you very much!

**Comment by mcmtroffaes** [comment]
If cddlib does then it might be possible to expose it in pycddlib. I'm not sure however that it does...

**Comment by CWEzio** [comment]
Thank you for your reply! It seems that cddlib do not have this functionality.
