### ISSUE TITLE
Help Regarding Installation

### ISSUE THREAD

**Issue by arshad171** [mcmtroffaes/pycddlib#63]
Hi,

I have a Fedora production server where I am trying to install `cdd`.  I came across the following [documentation](https://pycddlib.readthedocs.io/en/latest/quickstart.html#installation) and installed the required dependencies

```bash
(rl-mo-env) [arshad@cloud-01 rl-crazyflie]$ dnf list --installed | grep 'gmp-devel\|python3-devel'
gmp-devel.x86_64                                     1:6.2.1-4.fc38                       @release                  
python3-devel.x86_64                                 3.11.4-1.fc38                        @Fedora.updates  
```

And then I could install `pycddlib` by first setting the include path and then pip install

```bash
(rl-mo-env) [arshad@cloud-01 rl-crazyflie]$ export CPPFLAGS=-I/usr/include/python3.11/
(rl-mo-env) [arshad@cloud-01 rl-crazyflie]$ pip install pycddlib --no-cache-dir
Collecting pycddlib
  Downloading pycddlib-2.1.7.tar.gz (159 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 159.3/159.3 kB 6.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pycddlib
  Building wheel for pycddlib (setup.py) ... done
  Created wheel for pycddlib: filename=pycddlib-2.1.7-cp39-cp39-linux_x86_64.whl size=959295 sha256=bf3756b09881cfc5bbb8d0b4a41904dd54307c8b3df5608741a18ed520b66cdd
  Stored in directory: /tmp/pip-ephem-wheel-cache-239xpvtp/wheels/98/17/36/aad8bfb8adccab39c7e94d60593c23a4f75ef4c5223f2d73ca
Successfully built pycddlib
Installing collected packages: pycddlib
Successfully installed pycddlib-2.1.7
```

However, I am unable to use or even import the library in my python code
I see the following error ```undefined symbol: PyDescr_IsData```

```python
(rl-mo-env) [arshad@cloud-01 rl-crazyflie]$ python
Python 3.9.18 (main, Sep  6 2023, 16:41:18) 
[GCC 13.2.1 20230728 (Red Hat 13.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cdd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/data/arshad/workspace/rl-crazyflie/rl-mo-env/lib/python3.9/site-packages/cdd.cpython-39-x86_64-linux-gnu.so: undefined symbol: PyDescr_IsData
>>> 
```

I would really appreciate your help!

Thanks,
Arshad

**Comment by mcmtroffaes** [comment]
There seems to be a mix of python version in play (I see both 3.11 and 3.9 in different parts of your build), so if I had to venture a guess, that's probably why it's not working.

**Comment by arshad171** [comment]
@mcmtroffaes Thanks for the quick reply!

> There seems to be a mix of python version in play (I see both 3.11 and 3.9 in different parts of your build), so if I had to venture a guess, that's probably why it's not working.

Thank you for spotting that. I will try to have a common python base and give it a try

**Comment by mcmtroffaes** [comment]
I'm glad you managed to make it work with Python 3.11.

As a next step for the Python 3.9 build, I suggest using "python -m pip install pycddlib" instead of "pip install pycddlib", that way you know 100% for sure you're using the pip that fits the correct python installation. Though the venv should get this right... but I can't see where else it might be going wrong.

Either way PyDescr_IsData is part of the Python API (for both python 3.9 and 3.11) so it looks like a shared library loading issue not specific to pycddlib itself (as far as I can tell).

**Comment by mcmtroffaes** [comment]
Also note it's using the cached version which might still be corrupted. Try clearing the cache first before the build.

**Comment by arshad171** [comment]
Thank you!

That worked. Setting the `CPPFLAGS` to python 3.9 and `pip install pycddlib --no-cache` did a clean build
