### ISSUE TITLE
Any convenient way to do redundancy elimination of H-rep or V-rep?

### ISSUE THREAD

**Issue by FenglongSong** [mcmtroffaes/pycddlib#66]
Dear Matthias,

Thanks for creating this great python wrapper. I'm using _pycddlib_ in my project and it's working greatly well. I'd like to ask if there is any convenient way to do redundancy elimination in _pycddlib_. 

From the documentation of newest version of _cddlib_, it seems we can do this conveniently using `dd_MatrixCanonicalize()`. I want to confirm if this is covered in _pycvdlib_.

Thank you very much!

**Comment by mcmtroffaes** [comment]
Yes, glad you found it!
