### ISSUE TITLE
Volume calculation for polyhedron

### ISSUE THREAD

**Issue by lijiaying** [mcmtroffaes/pycddlib#67]
I wonder if it is possible to expose the volume calculation interface for users?
For example, when we have a convex polyhedron, we may interested in its volume which is not available in the current pycddlib version.

**Comment by mcmtroffaes** [comment]
Sure, I'm happy to take a PR that exposes any additional functions from cddlib. Alternatively, if you can point me to the correct function in cddlib, that would be very helpful too.

**Comment by mcmtroffaes** [comment]
Closing as I can't find the cddlib function that exposes this (https://github.com/search?q=repo%3Acddlib%2Fcddlib%20volume&type=code)... It seems this is not available. Happy to reopen if proven otherwise.
