### ISSUE TITLE
Issue with cdd.Matrix(m)

### ISSUE THREAD

**Issue by bxlliu** [mcmtroffaes/pycddlib#77]
Error when running this code:

> import numpy as np
> import cdd
> A = np.array([[0,1,0,1,0], [0,0,1,0,1], [1,0,0,0,1], [0,1,1,0,0], [1,0,0,0,0]])
> K = A - A.transpose()
> C = np.vstack( (K, -np.eye(5), [1]*5) )
> b = [[0]]*10 + [[1]]
> M = np.hstack( (b, -C) )
> mat = cdd.Matrix(M, linear=False, number_type="fraction") 
> mat.rep_type = cdd.RepType.INEQUALITY

Error: `TypeError: __init__() takes exactly 0 positional arguments (1 given)`

Reverting back to pycddlib 2.1.8.post1 fixes this issue

**Comment by bobmyhill** [comment]
Have you read the release notes for version 3.0.0? There are some breaking changes. https://pycddlib.readthedocs.io/en/latest/changes.html#version-3-0-0-4-october-2024

If you address these in your own code, the error should go away.

**Comment by mcmtroffaes** [comment]
Thank you for reporting and @bobmyhill for chiming in with the relevant pointer.

Indeed, there are many breaking changes the with 3.0.0 version. Please read the documentation first, and that should hopefully sort all problems when using the latest version. For constructing rational matrices, specifically, you should use the ``cdd.gmp.matrix_from_array`` function:

https://pycddlib.readthedocs.io/en/latest/cdd.html#cdd.matrix_from_array
https://pycddlib.readthedocs.io/en/latest/cddgmp.html

**Comment by bxlliu** [comment]
Got it, I see this is by design. Thank you!
