### ISSUE TITLE
Matrix raises TypeError

### ISSUE THREAD

**Issue by chengzhangli7** [mcmtroffaes/pycddlib#79]
I attempted to use **pycddlib ** to find vertices in a polytope with Python.  However, python reports the following error message:

Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\PythonProject\.venv\main.py", line 10, in <module>
    mat = pcdd.Matrix(M, linear=False, number_type="fraction")
TypeError: __init__() takes exactly 0 positional arguments (1 given)

The bug is associated with the use of the class "Matrix." For more details, please see the post on StackOverflow.

**Comment by chengzhangli7** [comment]
https://stackoverflow.com/questions/79294583/pycddlib-for-finding-all-vertices-in-a-polytope-python

**Comment by mcmtroffaes** [comment]
If you wish to use the old interface (the code that you posted seems to follow that), you must downgrade pycddlib to pre-3.0.0.

If you wish to upgrade your code for the new 3.x interface, the changelog may provide some guidance:

https://pycddlib.readthedocs.io/en/latest/changes.html#version-3-0-0-4-october-2024

If you just want to get something running quickly for the latest version, you can find an example for finding extreme points here:

https://pycddlib.readthedocs.io/en/latest/examples.html#calculating-extreme-points-rays

I hope this helps. If you still have issues after reading and following the documentation, please do reach out.

**Comment by chengzhangli7** [comment]
Thank you so much for your help! The new interface works!

I just have a clarification question. For the example of calculating extreme points that you provided (https://pycddlib.readthedocs.io/en/latest/examples.html#calculating-extreme-points-rays), what is the format of the output "ext.array"? In this example, it seems that [0,2,0], [0,0,0], [2,0,0], are the extreme points. How to interpret the first column and the last row.  What do they represent? Thanks!

**Comment by mcmtroffaes** [comment]
I'm glad this works for you, I think the issue can be closed.

Please refer to the documentation for a description of all Matrix attributes: https://pycddlib.readthedocs.io/en/latest/cdd.html#cdd.Matrix
